### ISSUE TITLE
Add information about the requirement of a database in the development section of README

### ISSUE THREAD

**Issue by IotaBread** [cardillan/mindcode#20]
As the title says, there isn't any information about the need of a PostgreSQL database in the README. The first time I tried to run it locally I spent some time trying to figure out why it didn't work.
Also, please add a note about the `JDBC_DATABASE_URL` in the readme, and how to pass credentials with it. (for example, adding `?user=<user>&password=<password>` to the end of the URL)

**Comment by francois** [comment]
Ooops, good point. I completely forgot about that. I'm so used to always having a DB, I never even thought about that. I'll improve this.

**Comment by cyclotron3k** [comment]
I set up an environment using docker & docker compose.

**Dockerfile**
```
FROM openjdk:11

WORKDIR /srv

RUN apt update && apt -y install maven

COPY . .

RUN mvn clean compile

EXPOSE 8080

CMD mvn exec:java
```

**docker-compose.yml**
```
version: '3.7'

services:

  mindcode-db:
    image: postgres:13
    restart: on-failure
    environment:
      POSTGRES_DB: mindcode_development
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pg_password
    volumes:
      - mindcode-postgres-data:/var/lib/postgresql/data
    ports:
      - 127.0.0.1:5432:5432

  mindcode-web:
    build:
      context: .
    environment:
      JDBC_DATABASE_URL: jdbc:postgresql://mindcode-db/mindcode_development?user=postgres&password=pg_password
    depends_on:
      - mindcode-db
    ports:
      - 127.0.0.1:8080:8080

volumes:
  mindcode-postgres-data:
    driver: local
```

I can make a PR for the two files if you think it would be useful.
